version: '3'
services:
  chat-gpt-api:
    image: "d0ckmg/free-gpt4-web-api:latest"
    ports:
      - "8081:5500"
  newsjourney-services-container:
    build:
      context: newsjourney-services
      dockerfile: ./Dockerfile.jvm
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
  midjourney-ui-container:
     image: erictik/midjourney-ui:latest
     #build:
      # context: midjourney-ui
      # dockerfile: ./Dockerfile
     #command: npm start
     env_file:
       - .env
     ports:
      - "3000:3000"
     restart: always
